build:api:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet --info
    - dotnet restore
    - dotnet build

build:angular:
  image: node:latest
  script:
    - pwd
    - cd web
    - yarn install
    - yarn run ng build

test:angular:
  image: debian:stable
  script:
    - apt-get update
    - apt-get install -yqq firefox-esr curl
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    - pwd
    - export NVM_DIR="$HOME/.nvm"
    - nvm install node
    - npm install -g yarn
    - cd web
    - yarn install
    - yarn run ng test --no-watch --no-progress --browsers=FirefoxHeadless

test:angularonfedora:
  image: fedora:latest
  script:
    - dnf check-update
    - dnf install -yqq firefox curl
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    - pwd
    - export NVM_DIR="$HOME/.nvm"
    - nvm install node
    - npm install -g yarn
    - cd web
    - yarn install
    - ng test --no-watch --no-progress --browsers=FirefoxHeadless

build:sql:
  image: mcr.microsoft.com/mssql/server:2019-latest
  variables:
    ACCEPT_EULA: Y
    SA_PASSWORD: 9034725985
  script:
    - cd data/terlinguasql
    - pwd
