build:api:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet --info
    - dotnet restore
    - dotnet build

build:angular:
  image: node:latest
  script:
    - pwd
    - cd web
    - yarn install
    - yarn run ng build
