build:api:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - dotnet --info
    - dotnet restore
    - dotnet build

build:angular:
  image: node:latest
  script:
    - pwd
    - cd web
    - yarn install
    - yarn run ng build

test:angular:
  image: debian:stable
  script:
    - rm /bin/sh && ln -s /bin/bash /bin/sh
    - time apt-get update
    - apt-get install -y -q --no-install-recommends apt-transport-https
    - apt-get install -y -q --no-install-recommends build-essential
    - apt-get install -y -q --no-install-recommends ca-certificates
    - apt-get install -y -q --no-install-recommends curl
    - apt-get install -y -q --no-install-recommends git
    - apt-get install -y -q --no-install-recommends libssl-dev
    - apt-get install -y -q --no-install-recommends wget
    - apt-get install -y -q --no-install-recommends firefox-esr
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
        && . /usr/local/nvm/nvm.sh \
        && nvm install node
    - node --version
    - npm --version
    - npm install -g yarn
    - cd web
    - yarn install
    - yarn run ng test --no-watch --no-progress --browsers=FirefoxHeadless

build:sql:
  image: mcr.microsoft.com/mssql/server:2019-latest
  variables:
    ACCEPT_EULA: Y
    SA_PASSWORD: 9034725985
  script:
    - cd data/terlinguasql
    - pwd
